crm_bizstock/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

urlpatterns = [
    path('usuario/', include('transversal.urls')),
    path('', RedirectView.as_view(url='usuario/login/', permanent=False), name='root'),
    path('inventario/', include('inventario.urls')),
   
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

inventario/urls.py
from django.contrib import admin
from django.urls import path
from .views import ListCategoryView, NewCategoryView, EditCategoryView, DeleteCategoryView, ListSubCategoryView, NewSubCategoryView, EditSubCategoryView, DeleteSubCategoryView

app_name = 'inventario'
urlpatterns = [
    path('categorias/', ListCategoryView.as_view(), name='list_category'),
    path('categorias/nueva', NewCategoryView.as_view(), name='new_category'),
    path('categorias/editar/<int:pk>', EditCategoryView.as_view(), name='edit_category'),
    path('categorias/eliminar/<int:pk>', DeleteCategoryView.as_view(), name='delete_category'),
    #Sub Categorías
    path('subcategorias/', ListSubCategoryView.as_view(), name='list_subcategory'),
    path('subcategorias/nueva', NewSubCategoryView.as_view(), name='new_subcategory'),
    path('subcategorias/editar/<int:pk>', EditSubCategoryView.as_view(), name='edit_subcategory'),
    path('subcategorias/eliminar/<int:pk>', DeleteSubCategoryView.as_view(), name='delete_subcategory'),
    #Marcas
    path('marcas/', ListSubCategoryView.as_view(), name='list_brand'),
    path('marcas/nueva', NewSubCategoryView.as_view(), name='new_brand'),
    path('marcas/editar/<int:pk>', EditSubCategoryView.as_view(), name='edit_brand'),
    path('marcas/eliminar/<int:pk>', DeleteSubCategoryView.as_view(), name='delete_brand'),
    #Unidad de Medida
    path('medidas/', ListSubCategoryView.as_view(), name='list_measure'),
    path('medidas/nueva', NewSubCategoryView.as_view(), name='new_measure'),
    path('medidas/editar/<int:pk>', EditSubCategoryView.as_view(), name='edit_measure'),
    path('medidas/eliminar/<int:pk>', DeleteSubCategoryView.as_view(), name='delete_measure'),
    #Producto
    path('productos/', ListSubCategoryView.as_view(), name='list_product'),
    path('productos/nueva', NewSubCategoryView.as_view(), name='new_product'),
    path('productos/editar/<int:pk>', EditSubCategoryView.as_view(), name='edit_product'),
    path('productos/eliminar/<int:pk>', DeleteSubCategoryView.as_view(), name='delete_product'),
]

inventario/models.py
from django.db import models
from transversal.models import BaseManage
# Create your models here.

class Category(BaseManage):
    description = models.CharField(
        max_length=150,
        help_text="Descripción de la categoría",
        null=True,
        blank= True,
    )
    def __str__(self):
        return '{}'.format(self.name)
    class Meta:
        verbose_name_plural = "Categorias"

class SubCategory(BaseManage):
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL, null=True,
        verbose_name="Categoría Asociada",
        default=None
    )
    description = models.CharField(
        max_length=150,
        verbose_name="Descripción de la Sub Categoría",
        null=True,
        blank= True,
    )
    def __str__(self):
        return '{} - {}'.format(self.category.name, self.name)
    
    class Meta:
        verbose_name_plural = "Subcategorias"

class Marca(BaseManage):
    description = models.CharField(
        max_length=100, 
        verbose_name ='Descripción de la marca', 
        unique=True,
        null=True,
        blank= True,
        )

    def __str__(self):
        return '{}'.format(self.name)

    class Meta:
        verbose_name_plural = "Marcas"

class UnidadMedida(BaseManage):
    description = models.CharField(
        max_length=100, 
        verbose_name ='Descripción de la unidad de medida', 
        unique=True,
        null=True,
        blank= True,
    )

    def __str__(self):
        return '{}'.format(self.name)

    class Meta:
        verbose_name_plural = "Unidades de medida"


class Product(BaseManage):
    code_sku = models.CharField(
        max_length=20, 
        unique=True,
        verbose_name ="Código Sku",
    )
    bar_code = models.CharField(
        max_length=50,
        verbose_name="Código de Barras",
    )
    description = models.CharField(
        max_length=200, 
        verbose_name ='Descripción del Producto', 
        unique=True,
        null=True,
        blank= True,
    )
    price = models.PositiveIntegerField(
        default=0,
        verbose_name ='Precio Unitario del Producto',
        null=False,
        blank= False,
    )
    current_existence = models.IntegerField(
        default=0,
        verbose_name = "Existencia en Inventarios",
        null=False,
        blank= False,
    )
    last_purchase_date = models.DateField(
        verbose_name= "Fecha de última Compra",
        null=True, 
        blank=True,
    )
    brand = models.ForeignKey(
        Marca, on_delete=models.SET_NULL, null=True,
        verbose_name="Marca Asociada",
        default=None
    )
    unit_measure = models.ForeignKey(
        UnidadMedida, on_delete=models.SET_NULL, null=True,
        verbose_name="Unidad de Medida Asociada",
     )
    sub_category = models.ForeignKey(
        SubCategory, on_delete=models.SET_NULL, null=True,
        verbose_name="Sub Categoría Asociada",
        )
    #privider

    def __str__(self):
        return '{}'.format(self.name)

    class Meta:
        verbose_name_plural = "Productos"

inventario/views.py
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.views import generic
from django.urls import reverse_lazy
from .models import Category, SubCategory, Marca, UnidadMedida, Product
from .form import CategoryForm, SubCategoryForm

# Create your views here.

class ListCategoryView(generic.ListView):
    model = Category
    template_name = "category/category_list.html"
    context_object_name = "categories"
    ordering = ['id']

class NewCategoryView(SuccessMessageMixin, generic.CreateView):
    model = Category
    template_name = "category/category_new.html"
    context_object_name = "categoria"
    form_class = CategoryForm
    success_url = reverse_lazy ('inventario:list_category')
    success_message = "Categoríoa creada satisfactoriamente"

    # agregamos el usuario que realiza la modificación
    def form_valid(self, form):
        form.instance.user_created = self.request.user.username

        return super().form_valid(form)

class EditCategoryView(SuccessMessageMixin, generic.UpdateView):
    model = Category
    template_name = "category/category_new.html"
    context_object_name = "categoria"
    form_class = CategoryForm
    success_url = reverse_lazy ('inventario:list_category')
    success_message = "Categoría ctualizada"

    def form_valid(self, form):
        form.instance.user_created = self.request.user.username

        return super().form_valid(form)

class DeleteCategoryView(SuccessMessageMixin, generic.DeleteView):
    model = Category
    template_name = "category/category_delete.html"
    success_url = reverse_lazy("inventario:list_category")
    success_message = "La categoría ha sido eliminada correctamente"
#SUB CATEGORIAS
class ListSubCategoryView(generic.ListView):
    model = SubCategory
    template_name = "sub_category/sub_category_list.html"
    context_object_name = "subcategories"
    ordering = ['id']

class NewSubCategoryView(SuccessMessageMixin, generic.CreateView):
    model = SubCategory
    template_name = "sub_category/sub_category_new.html"
    context_object_name = "subcategoria"
    form_class = SubCategoryForm
    success_url = reverse_lazy ('inventario:list_subcategory')
    success_message = "Categoríoa creada satisfactoriamente"

    # agregamos el usuario que realiza la modificación
    def form_valid(self, form):
        form.instance.user_created = self.request.user.username

        return super().form_valid(form)

class EditSubCategoryView(SuccessMessageMixin, generic.UpdateView):
    model = SubCategory
    template_name = "sub_category/sub_category_new.html"
    context_object_name = "subcategoria"
    form_class = SubCategoryForm
    success_url = reverse_lazy ('inventario:list_subcategory')
    success_message = "Categoría ctualizada"

    def form_valid(self, form):
        form.instance.user_created = self.request.user.username

        return super().form_valid(form)

class DeleteSubCategoryView(SuccessMessageMixin, generic.DeleteView):
    model = SubCategory
    template_name = "sub_category/sub_category_delete.html"
    success_url = reverse_lazy("inventario:list_subcategory")
    success_message = "La categoría ha sido eliminada correctamente"

#brand

class ListBrandView(generic.ListView):
    model = Marca
    template_name = "brand/brand_list.html"
    context_object_name = "brand"
    ordering = ['id']

# class NewCategoryView(SuccessMessageMixin, generic.CreateView):
#     model = Category
#     template_name = "category_new.html"
#     context_object_name = "categoria"
#     form_class = CategoryForm
#     success_url = reverse_lazy ('inventario:list_category')
#     success_message = "Categoríoa creada satisfactoriamente"

#     # agregamos el usuario que realiza la modificación
#     def form_valid(self, form):
#         form.instance.user_created = self.request.user.username

#         return super().form_valid(form)

# class EditCategoryView(SuccessMessageMixin, generic.UpdateView):
#     model = Category
#     template_name = "category_new.html"
#     context_object_name = "categoria"
#     form_class = CategoryForm
#     success_url = reverse_lazy ('inventario:list_category')
#     success_message = "Categoría ctualizada"

#     def form_valid(self, form):
#         form.instance.user_created = self.request.user.username

#         return super().form_valid(form)

# class DeleteCategoryView(SuccessMessageMixin, generic.DeleteView):
#     model = Category
#     template_name = "category_delete.html"
#     success_url = reverse_lazy("inventario:list_category")
#     success_message = "La categoría ha sido eliminada correctamente"

inventario/templates/sub_category/sub_category_delete.html
{% extends 'base.html' %}
{% block content %}
<form method="POST" class="form-inline">
  {% csrf_token %}
  <div class="col-xl-3 col-md-6 mb-4">
    <div class="card border-left-danger shadow h-100 py-2">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-success text-uppercase mb-1">¿Eliminar {{ obj.descripcion }}?</div>
            <div class="d-flex">
              <button type="submit" class="btn btn-danger mr-2">Eliminar</button>
              <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-success">Cancelar</a>
            </div>
          </div>
          <div class="col-auto"><i class="far fa-question-circle fa-2x text-gray-300"></i></div>
        </div>
      </div>
    </div>
  </div>
</form>
{% endblock %}
{% block javascript %}{% endblock %}

inventario/templates/sub_category/sub_category_list.html
{% extends "base.html" %}

{% block content %}

<!--Pantilla-->
    <div class="container-fluid py-4">
      <div class="row">
        <div class="col-12">
          <div class="card my-4">
            <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
              <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
              <div class="col-9">
                <h6 class="text-white text-capitalize ps-3">Listado de SubCategorías</h6>
                </div>
                <div class="col-3">
                <a href="{% url 'inventario:new_subcategory' %}" class="btn btn-info btn-circle" role="button"><i class="far fa-new"></i>Nueva SubCategoría</a>
                </div>
              </div>
            </div>
            {% if not subcategories %}
                <p >No hay categorías</p>
          {% else %}
            <div class="card-body px-0 pb-2">
              <div class="table-responsive p-0">
                <table class="table align-items-center mb-0">
                  <thead>
                    <tr>
                      <th>Id</th>
                      <th>Categoría</th>
                      <th>Nombre</th>
                      <th>Descripción</th>
                      <th>Fecha creación</th>
                      <th>Fecha modificación</th>
                      <th class="all">Acciones </th>
                    </tr>
                  </thead>
                  <tbody>
                  {% for category in subcategories %}
        <tr>
          <td>{{ category.id }}</td>
          <td>{{ category.category }}</td>
          <td>{{ category.name }}</td>
          <td>{{ category.description }}</td>          
          <td>{{ category.created_date|date:"d/m/Y H:i:s" }}</td>
          <td>{{ category.modified_date|date:"d/m/Y H:i:s" }}</td>
          <td>
            <a href="{% url 'inventario:edit_subcategory' category.id %}" class="btn btn-warning btn-circle" role="button"><i class="far fa-edit"></i></a>
            <a href="{% url 'inventario:delete_subcategory' category.id %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-trash-alt"></i></a>
            {% comment %} <button class="btn btn-danger btn-circle" role="button" data-toggle="modal" data-target="#deleteModal{{ category.id }}">
              <i class="far fa-trash-alt"></i>
            </button>           {% endcomment %}
          </td>
        </tr>

        <!-- Modal de confirmación para eliminar -->
        <div class="modal fade" id="deleteModal{{ category.id }}" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Confirmación de Eliminación</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                ¿Estás seguro de que deseas eliminar esta Sucategoría?
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <a href="{% url 'inventario:delete_category' category.id %}" class="btn btn-danger">Eliminar</a>
              </div>
            </div>
          </div>
        </div>

        {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
{% endblock %}

{% block javascript %}{% endblock %}

inventario/templates/sub_category/sub_category_new.html
{% extends 'base.html' %}
{% block content %}

<form method="POST" class="form-inline">
  {% csrf_token %}
  <div class="col-xl-6 col-md-6 mb-6">
    {% if subcategoria %}
    <div class="card border-left-warning shadow h-100 py-2">
    {% else %}
      <div class="card border-left-success shadow h-100 py-2">
    {% endif %}
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-success text-uppercase mb-1">{% if subcategoria %} Editar {% else %} Nueva {% endif %} SubCategoría</div>
            <div class="dropdown-divider"></div>
            <div class="row">
              <div class="col-6">
                <div class="form-group">
                    <label for="{{ form.category.label }}">Categoría Asociada </label>
                    {{ form.category }}
                </div>
              </div>
              <div class="col-6">
              <label for="{{ form.name.label }}">Nombre SubCategoría</label>
                <div class="input-group">                
                  <input type="text" name="name" maxlength="100" id="name" class="form-control" placeholder="Nombre" value="{% if subcategoria %} {{ subcategoria.name }} {% endif %}" required>
                </div>
              </div>
              <div class="col-10">
              <label for="{{ form.description.label }}">Descripción: </label>
                <div class="input-group">
                  <input type="text" name="description" maxlength="100" id="description" class="form-control" placeholder="Descripción" value="{% if subcategoria %} {{ subcategoria.description }} {% endif %}" required>
                </div>
              </div>
              <div class="col-2">
                <div class="form-group">
                  <label for="state" class="mr-2">Estado:</label>
                  <input type="checkbox" name="state"  id="state" {% if subcategoria.state %} checked {% endif %}>
                </div>
              </div>
            </div>
            <div class="dropdown-divider"></div>
            <div class="row">
              <div class="col">
                <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Guardar</button>
                <a href="{% url 'inventario:list_subcategory' %}" class="btn btn-success"><span class="fa fa-undo"></span> Cancelar</a>
              </div>
            </div>
          </div>
        </div>
      </div>
      </div>
    </div>
  </div>
</form>
{% endblock %}
{% block javascript %}{% endblock %}